### ISSUE TITLE
Reset Pin not set up correctly for Waveshare device

### ISSUE THREAD

**Issue by corranwebster** [unital/tempe#77]
_Originally posted by @JoGeDuBo in https://github.com/unital/tempe/issues/60#issuecomment-2521315122_

> Found the error why nothing was shown on the waveshare display in base.py, line 107
> 
> ```
>         if isinstance(reset_pin, int):
>             # reset_pin = Pin(reset_pin, Pin.OUT) # wrong
>             reset_pin = Pin(reset_pin, Pin.OUT, value=True) # right 
> ```
> 
> and lines 131, 132 could be left out:
> 
> ```
>             self.reset_pin(True)
>             asyncio.sleep(0.500)
> ```
> 
> and, as in my penultimate post:
> in waveshare.py, line 28,29
> 
> ```
>             spi = SPI(
>                 # 0, # wrong
>                 1, # right
> ```
>

**Comment by JoGeDuBo** [comment]
actual base.py on Pico-ResTouch-LCD-2.8 tested: works.
