### ISSUE TITLE
Clock Example

### ISSUE THREAD

**Issue by thestumbler** [unital/tempe#84]
I really like the appearance of this example! Great job.

I notice there is a tiny remnant of the second hand lingering at the 29 and 44 second position.
![IMG_0682](https://github.com/user-attachments/assets/50a7b83f-1cc3-4f0f-b56f-e5b345420635)

**Comment by thestumbler** [comment]
Fun fact which hit me when I was figuring out the function call that drew those 12 numbers of the clock face. Did you know that clocks using Arabic numerals, the digits are oriented vertically as you've done here, but for clock faces using Roman numerals, the "digit" orientation rotates according to the position, sign that the "V" of 5 o'clock is almost upside down?

**Comment by corranwebster** [comment]
Thanks - that it looks like a bug in the update code for lines.  I think I have a fix for that.

I didn't know that about the traditional arrangement of roman numerals, but that is something which Tempe currently lacks is the ability to render text at different angles.  I should probably add an issue for that.

**Comment by thestumbler** [comment]
I'll check this soon. Looking at some random VU meter pictures online, I'd say there's a mixture of vertically aligned digits and rotated digits (aligned with the tick marks). I can live with non-rotated text. 

Thinking back on your stated goals, which include making pretty plots, seems like rotated text would be needed. At minimum 90 deg increments for Y-axis labels. Arbitrary for more fancy plots.
